# Generated by Django 6.0.8 on 2026-09-07 02:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('cpf_cnpj', models.TextField(blank=True, null=True)),
                ('telefone', models.TextField(blank=True, null=True)),
                ('rua_numero', models.TextField(blank=True, null=True)),
                ('bairro', models.TextField(blank=True, null=True)),
                ('cidade', models.TextField(blank=True, default='Cataguases', null=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('senha', models.TextField()),
                ('cpf', models.TextField(blank=True, null=True)),
                ('telefone', models.TextField(blank=True, null=True)),
                ('role', models.TextField(default='VENDEDOR')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'funcionarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValorCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_cliente', models.UUIDField()),
                ('id_produto', models.UUIDField()),
                ('valor_especifico', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'valor_cliente',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='DeliveryDriver',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
