  spring:

    datasource:
      url: jdbc:postgresql://db.mhxycuagyraepaxmpekg.supabase.co:5432/postgres
      username: postgres
      password: fagocitose!

    jpa:
      hibernate:
        ddl-auto: validate

      properties:
        hibernate:
          format_sql: true

      show-sql: true

  server:
    port: 8080
